--------------------------------------------------------
--  Fichier créé - jeudi-mai-06-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence DEPENSE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."DEPENSE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FOURNISSEURS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."FOURNISSEURS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FOURN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."FOURN_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FOURN_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."FOURN_SEQ1"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FOURN_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."FOURN_SEQ2"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FOURN_SEQ3
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."FOURN_SEQ3"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FOURN_SEQ4
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."FOURN_SEQ4"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LIVRAISON_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."LIVRAISON_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LIVRAISON_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."LIVRAISON_SEQ1"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LIVREUR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."LIVREUR_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MAINTENANCE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."MAINTENANCE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRODUIT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."PRODUIT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REVENU_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."REVENU_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STOCK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."STOCK_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STOCK_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."STOCK_SEQ1"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STOCK_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."STOCK_SEQ2"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STOCK_SEQ3
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."STOCK_SEQ3"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STOCK_SEQ4
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."STOCK_SEQ4"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STOCK_SEQ5
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."STOCK_SEQ5"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STOCK_SEQ6
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."STOCK_SEQ6"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "TAIEF"."CLIENT" 
   (	"ID_CLI" NUMBER, 
	"NOM_CLI" VARCHAR2(255 BYTE), 
	"PRENOM_CLI" VARCHAR2(255 BYTE), 
	"NUM_TEL" NUMBER, 
	"ADRESSE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "TAIEF"."COMMANDE" 
   (	"ID_COM" NUMBER, 
	"DATE_COM" VARCHAR2(255 BYTE), 
	"NOMBRE_COME" NUMBER, 
	"TYPE_COM" VARCHAR2(255 BYTE), 
	"ID_CLI" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEPENSE
--------------------------------------------------------

  CREATE TABLE "TAIEF"."DEPENSE" 
   (	"ID_DEP" NUMBER, 
	"TOT_DEP" NUMBER, 
	"TYPE_DEP" VARCHAR2(255 BYTE), 
	"DATE_DEP" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURN
--------------------------------------------------------

  CREATE TABLE "TAIEF"."FOURN" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(255 BYTE), 
	"PRENOM" VARCHAR2(255 BYTE), 
	"TEL" NUMBER, 
	"ADRESSE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIVRAISON
--------------------------------------------------------

  CREATE TABLE "TAIEF"."LIVRAISON" 
   (	"ID" NUMBER, 
	"ADH" VARCHAR2(255 BYTE), 
	"DATEE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIVREUR
--------------------------------------------------------

  CREATE TABLE "TAIEF"."LIVREUR" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(255 BYTE), 
	"PRENOM" VARCHAR2(255 BYTE), 
	"NUMTEL" NUMBER, 
	"SALAIRE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONNEL
--------------------------------------------------------

  CREATE TABLE "TAIEF"."PERSONNEL" 
   (	"ID" VARCHAR2(255 BYTE), 
	"NOM" VARCHAR2(255 BYTE), 
	"PRENOM" VARCHAR2(255 BYTE), 
	"MDP" VARCHAR2(255 BYTE), 
	"DATE_EMB" VARCHAR2(255 BYTE), 
	"SALAIRE" NUMBER, 
	"TYPE" VARCHAR2(255 BYTE), 
	"IMAGE" BLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("IMAGE") STORE AS (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "TAIEF"."PRODUIT" 
   (	"ID_PRODUIT" NUMBER, 
	"NOM_PRODUIT" VARCHAR2(255 BYTE), 
	"TYPE_PRODUIT" VARCHAR2(255 BYTE), 
	"TOT_PRODUIT" NUMBER, 
	"DATE_PRODUIT" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROFIL
--------------------------------------------------------

  CREATE TABLE "TAIEF"."PROFIL" 
   (	"ID" VARCHAR2(255 BYTE), 
	"LOGIN" VARCHAR2(255 BYTE), 
	"MDP" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REVENU
--------------------------------------------------------

  CREATE TABLE "TAIEF"."REVENU" 
   (	"ID_REV" NUMBER, 
	"TOT_REV" NUMBER, 
	"TYPE_REV" VARCHAR2(255 BYTE), 
	"DATE_REV" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STOCK
--------------------------------------------------------

  CREATE TABLE "TAIEF"."STOCK" 
   (	"ID" NUMBER, 
	"DAT" VARCHAR2(255 BYTE), 
	"PRIX" NUMBER, 
	"QUANTITE" NUMBER, 
	"NOM" VARCHAR2(255 BYTE), 
	"TYPE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TAIEF.CLIENT
SET DEFINE OFF;
Insert into TAIEF.CLIENT (ID_CLI,NOM_CLI,PRENOM_CLI,NUM_TEL,ADRESSE) values ('1','ckjnjkv','jksqndfcj','56556','ejkfhj');
Insert into TAIEF.CLIENT (ID_CLI,NOM_CLI,PRENOM_CLI,NUM_TEL,ADRESSE) values ('10','daly','ddd','555','ccc');
Insert into TAIEF.CLIENT (ID_CLI,NOM_CLI,PRENOM_CLI,NUM_TEL,ADRESSE) values ('30','cjncj','mx;c','656','tuniis');
REM INSERTING into TAIEF.COMMANDE
SET DEFINE OFF;
Insert into TAIEF.COMMANDE (ID_COM,DATE_COM,NOMBRE_COME,TYPE_COM,ID_CLI) values ('12','cc','5','sur place','10');
Insert into TAIEF.COMMANDE (ID_COM,DATE_COM,NOMBRE_COME,TYPE_COM,ID_CLI) values ('111','cc','5','sur place','1');
Insert into TAIEF.COMMANDE (ID_COM,DATE_COM,NOMBRE_COME,TYPE_COM,ID_CLI) values ('2','5 mars','5','sur place','10');
Insert into TAIEF.COMMANDE (ID_COM,DATE_COM,NOMBRE_COME,TYPE_COM,ID_CLI) values ('11','5 mars','5','sur place','10');
Insert into TAIEF.COMMANDE (ID_COM,DATE_COM,NOMBRE_COME,TYPE_COM,ID_CLI) values ('10','6 mars','5454','sur place','10');
Insert into TAIEF.COMMANDE (ID_COM,DATE_COM,NOMBRE_COME,TYPE_COM,ID_CLI) values ('30','6 mars 2020','5454','sur place','10');
REM INSERTING into TAIEF.DEPENSE
SET DEFINE OFF;
Insert into TAIEF.DEPENSE (ID_DEP,TOT_DEP,TYPE_DEP,DATE_DEP) values ('11','152','type1','01/01/2000');
Insert into TAIEF.DEPENSE (ID_DEP,TOT_DEP,TYPE_DEP,DATE_DEP) values ('100','160','type1','01/01/2000');
Insert into TAIEF.DEPENSE (ID_DEP,TOT_DEP,TYPE_DEP,DATE_DEP) values ('444','2000','type1','01/01/2000');
REM INSERTING into TAIEF.FOURN
SET DEFINE OFF;
REM INSERTING into TAIEF.LIVRAISON
SET DEFINE OFF;
REM INSERTING into TAIEF.LIVREUR
SET DEFINE OFF;
Insert into TAIEF.LIVREUR (ID,NOM,PRENOM,NUMTEL,SALAIRE) values ('1','dc','dd','633','100');
Insert into TAIEF.LIVREUR (ID,NOM,PRENOM,NUMTEL,SALAIRE) values ('2','dc','ddkkk','633','500');
Insert into TAIEF.LIVREUR (ID,NOM,PRENOM,NUMTEL,SALAIRE) values ('3','dc','ddkkk','633','1000');
REM INSERTING into TAIEF.PERSONNEL
SET DEFINE OFF;
REM INSERTING into TAIEF.PRODUIT
SET DEFINE OFF;
Insert into TAIEF.PRODUIT (ID_PRODUIT,NOM_PRODUIT,TYPE_PRODUIT,TOT_PRODUIT,DATE_PRODUIT) values ('25','ddd','fastfood','55','04/01/2020');
Insert into TAIEF.PRODUIT (ID_PRODUIT,NOM_PRODUIT,TYPE_PRODUIT,TOT_PRODUIT,DATE_PRODUIT) values ('88','ljkj','fastfood','0','03/05/2000');
REM INSERTING into TAIEF.PROFIL
SET DEFINE OFF;
REM INSERTING into TAIEF.REVENU
SET DEFINE OFF;
Insert into TAIEF.REVENU (ID_REV,TOT_REV,TYPE_REV,DATE_REV) values ('1','1577','type1','01/01/2000');
Insert into TAIEF.REVENU (ID_REV,TOT_REV,TYPE_REV,DATE_REV) values ('12','100','type1','01/01/2000');
Insert into TAIEF.REVENU (ID_REV,TOT_REV,TYPE_REV,DATE_REV) values ('55','10000','type1','01/01/2000');
REM INSERTING into TAIEF.STOCK
SET DEFINE OFF;
Insert into TAIEF.STOCK (ID,DAT,PRIX,QUANTITE,NOM,TYPE) values ('1','02/01/2000 00:00','10','444','taiief','type1');
--------------------------------------------------------
--  DDL for Index LIVRAISON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."LIVRAISON_PK" ON "TAIEF"."LIVRAISON" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LIVREUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."LIVREUR_PK" ON "TAIEF"."LIVREUR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REVENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."REVENU_PK" ON "TAIEF"."REVENU" ("ID_REV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."CLIENT_PK" ON "TAIEF"."CLIENT" ("ID_CLI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSONNEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."PERSONNEL_PK" ON "TAIEF"."PERSONNEL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMANDE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."COMMANDE_PK" ON "TAIEF"."COMMANDE" ("ID_COM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROFIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."PROFIL_PK" ON "TAIEF"."PROFIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."PRODUIT_PK" ON "TAIEF"."PRODUIT" ("ID_PRODUIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STOCK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."STOCK_PK" ON "TAIEF"."STOCK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPENSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."DEPENSE_PK" ON "TAIEF"."DEPENSE" ("ID_DEP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."FOURN_PK" ON "TAIEF"."FOURN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger FOURN_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TAIEF"."FOURN_TRG" 
BEFORE INSERT ON FOURN 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT FOURN_SEQ4.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TAIEF"."FOURN_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LIVRAISON_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TAIEF"."LIVRAISON_TRG" 
BEFORE INSERT ON LIVRAISON 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT LIVRAISON_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TAIEF"."LIVRAISON_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LIVREUR_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TAIEF"."LIVREUR_TRG" 
BEFORE INSERT ON LIVREUR 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT LIVREUR_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TAIEF"."LIVREUR_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STOCK_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TAIEF"."STOCK_TRG" 
BEFORE INSERT ON STOCK 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT STOCK_SEQ6.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TAIEF"."STOCK_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table REVENU
--------------------------------------------------------

  ALTER TABLE "TAIEF"."REVENU" ADD CONSTRAINT "REVENU_PK" PRIMARY KEY ("ID_REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."REVENU" MODIFY ("ID_REV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPENSE
--------------------------------------------------------

  ALTER TABLE "TAIEF"."DEPENSE" ADD CONSTRAINT "DEPENSE_PK" PRIMARY KEY ("ID_DEP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."DEPENSE" MODIFY ("ID_DEP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONNEL
--------------------------------------------------------

  ALTER TABLE "TAIEF"."PERSONNEL" ADD CONSTRAINT "PERSONNEL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."PERSONNEL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STOCK
--------------------------------------------------------

  ALTER TABLE "TAIEF"."STOCK" ADD CONSTRAINT "STOCK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."STOCK" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROFIL
--------------------------------------------------------

  ALTER TABLE "TAIEF"."PROFIL" ADD CONSTRAINT "PROFIL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."PROFIL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LIVREUR
--------------------------------------------------------

  ALTER TABLE "TAIEF"."LIVREUR" ADD CONSTRAINT "LIVREUR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."LIVREUR" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "TAIEF"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID_CLI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."CLIENT" MODIFY ("ID_CLI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURN
--------------------------------------------------------

  ALTER TABLE "TAIEF"."FOURN" ADD CONSTRAINT "FOURN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."FOURN" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "TAIEF"."PRODUIT" ADD CONSTRAINT "PRODUIT_PK" PRIMARY KEY ("ID_PRODUIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."PRODUIT" MODIFY ("ID_PRODUIT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LIVRAISON
--------------------------------------------------------

  ALTER TABLE "TAIEF"."LIVRAISON" ADD CONSTRAINT "LIVRAISON_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."LIVRAISON" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "TAIEF"."COMMANDE" ADD CONSTRAINT "COMMANDE_PK" PRIMARY KEY ("ID_COM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."COMMANDE" MODIFY ("ID_COM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "TAIEF"."COMMANDE" ADD CONSTRAINT "FK_ID_CLI" FOREIGN KEY ("ID_CLI")
	  REFERENCES "TAIEF"."CLIENT" ("ID_CLI") ENABLE;
