--------------------------------------------------------
--  Fichier créé - vendredi-avril-16-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence FOURNISSEURS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."FOURNISSEURS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FOURN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."FOURN_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FOURN_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."FOURN_SEQ1"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FOURN_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."FOURN_SEQ2"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FOURN_SEQ3
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."FOURN_SEQ3"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STOCK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."STOCK_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STOCK_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."STOCK_SEQ1"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STOCK_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."STOCK_SEQ2"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STOCK_SEQ3
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."STOCK_SEQ3"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STOCK_SEQ4
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."STOCK_SEQ4"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STOCK_SEQ5
--------------------------------------------------------

   CREATE SEQUENCE  "TAIEF"."STOCK_SEQ5"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "TAIEF"."CLIENT" 
   (	"ID_CLI" NUMBER, 
	"NOM_CLI" VARCHAR2(255 BYTE), 
	"PRENOM_CLI" VARCHAR2(255 BYTE), 
	"NUM_TEL" NUMBER, 
	"ADRESSE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "TAIEF"."COMMANDE" 
   (	"ID_COM" NUMBER, 
	"DATE_COM" VARCHAR2(255 BYTE), 
	"NOMBRE_COME" NUMBER, 
	"TYPE_COM" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEPENSE
--------------------------------------------------------

  CREATE TABLE "TAIEF"."DEPENSE" 
   (	"ID_DEP" NUMBER, 
	"TOT_DEP" NUMBER, 
	"TYPE_DEP" VARCHAR2(255 BYTE), 
	"DATE_DEP" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURN
--------------------------------------------------------

  CREATE TABLE "TAIEF"."FOURN" 
   (	"ID" NUMBER(*,0), 
	"NOM" VARCHAR2(255 BYTE), 
	"PRENOM" VARCHAR2(255 BYTE), 
	"TEL" NUMBER(*,0), 
	"ADRESSE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIVRAISON
--------------------------------------------------------

  CREATE TABLE "TAIEF"."LIVRAISON" 
   (	"ID" NUMBER, 
	"ADR" VARCHAR2(255 BYTE), 
	"DATEE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIVREUR
--------------------------------------------------------

  CREATE TABLE "TAIEF"."LIVREUR" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(255 BYTE), 
	"PRENOM" VARCHAR2(255 BYTE), 
	"NUMTEL" NUMBER, 
	"SALAIRE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONNEL
--------------------------------------------------------

  CREATE TABLE "TAIEF"."PERSONNEL" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"MDP" VARCHAR2(20 BYTE), 
	"DATE_EMB" VARCHAR2(20 BYTE), 
	"SALAIRE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"IMAGE" BLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("IMAGE") STORE AS (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "TAIEF"."PRODUIT" 
   (	"ID_PRODUIT" NUMBER, 
	"NOM_PRODUIT" VARCHAR2(255 BYTE), 
	"TYPE_PRODUIT" VARCHAR2(255 BYTE), 
	"TOT_PRODUIT" NUMBER, 
	"PRODUIT_REV" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROFIL
--------------------------------------------------------

  CREATE TABLE "TAIEF"."PROFIL" 
   (	"ID" VARCHAR2(20 BYTE), 
	"LOGIN" VARCHAR2(20 BYTE), 
	"MDP" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REVENU
--------------------------------------------------------

  CREATE TABLE "TAIEF"."REVENU" 
   (	"ID_REV" NUMBER, 
	"TOT_REV" NUMBER, 
	"TYPE_REV" VARCHAR2(255 BYTE), 
	"DATE_REV" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STOCK
--------------------------------------------------------

  CREATE TABLE "TAIEF"."STOCK" 
   (	"ID" NUMBER(*,0), 
	"DAT" VARCHAR2(255 BYTE), 
	"PRIX" NUMBER, 
	"QUANTITE" NUMBER, 
	"NOM" VARCHAR2(255 BYTE), 
	"TYPE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TAIEF.CLIENT
SET DEFINE OFF;
REM INSERTING into TAIEF.COMMANDE
SET DEFINE OFF;
REM INSERTING into TAIEF.DEPENSE
SET DEFINE OFF;
REM INSERTING into TAIEF.FOURN
SET DEFINE OFF;
Insert into TAIEF.FOURN (ID,NOM,PRENOM,TEL,ADRESSE) values ('1','TAIEF','HILALI','555','ddd,tunis');
Insert into TAIEF.FOURN (ID,NOM,PRENOM,TEL,ADRESSE) values ('2','taiem','HILALI','97585787','ddd,Nabeul');
Insert into TAIEF.FOURN (ID,NOM,PRENOM,TEL,ADRESSE) values ('4','hamda','hamoud','97584789','ddd,Nabeul');
Insert into TAIEF.FOURN (ID,NOM,PRENOM,TEL,ADRESSE) values ('5','hh','ll','555','lmmmm,Nabeul');
Insert into TAIEF.FOURN (ID,NOM,PRENOM,TEL,ADRESSE) values ('6','bjbjlll','mlllkjnjk','54852155','tunis');
Insert into TAIEF.FOURN (ID,NOM,PRENOM,TEL,ADRESSE) values ('22','lllll','fffff','99','dafzlse');
REM INSERTING into TAIEF.LIVRAISON
SET DEFINE OFF;
REM INSERTING into TAIEF.LIVREUR
SET DEFINE OFF;
REM INSERTING into TAIEF.PERSONNEL
SET DEFINE OFF;
REM INSERTING into TAIEF.PRODUIT
SET DEFINE OFF;
REM INSERTING into TAIEF.PROFIL
SET DEFINE OFF;
REM INSERTING into TAIEF.REVENU
SET DEFINE OFF;
REM INSERTING into TAIEF.STOCK
SET DEFINE OFF;
Insert into TAIEF.STOCK (ID,DAT,PRIX,QUANTITE,NOM,TYPE) values ('1','sam. avr. 10 2021','10','650','ghada','type3');
Insert into TAIEF.STOCK (ID,DAT,PRIX,QUANTITE,NOM,TYPE) values ('2','mer. mars 17 2021','9922','97777','tebaasi','type3');
Insert into TAIEF.STOCK (ID,DAT,PRIX,QUANTITE,NOM,TYPE) values ('3','sam. avr. 10 2021','100','97','taiief','type1');
Insert into TAIEF.STOCK (ID,DAT,PRIX,QUANTITE,NOM,TYPE) values ('5','mer. avr. 14 2021','21245','9','kkk','type2');
Insert into TAIEF.STOCK (ID,DAT,PRIX,QUANTITE,NOM,TYPE) values ('21','ven. avr. 16 2021','100','56','daliiiiii','type1');
Insert into TAIEF.STOCK (ID,DAT,PRIX,QUANTITE,NOM,TYPE) values ('23','01/01/2021 08:00','1010','555','hammda','type1');
--------------------------------------------------------
--  DDL for Index LIVRAISON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."LIVRAISON_PK" ON "TAIEF"."LIVRAISON" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LIVREUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."LIVREUR_PK" ON "TAIEF"."LIVREUR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REVENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."REVENU_PK" ON "TAIEF"."REVENU" ("ID_REV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."CLIENT_PK" ON "TAIEF"."CLIENT" ("ID_CLI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMANDE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."COMMANDE_PK" ON "TAIEF"."COMMANDE" ("ID_COM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROFIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."PROFIL_PK" ON "TAIEF"."PROFIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."PRODUIT_PK" ON "TAIEF"."PRODUIT" ("ID_PRODUIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STOCK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."STOCK_PK" ON "TAIEF"."STOCK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."FOURN_PK" ON "TAIEF"."FOURN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPENSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TAIEF"."DEPENSE_PK" ON "TAIEF"."DEPENSE" ("ID_DEP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger FOURN_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TAIEF"."FOURN_TRG" 
BEFORE INSERT ON FOURN 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT FOURN_SEQ3.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TAIEF"."FOURN_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STOCK_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TAIEF"."STOCK_TRG" 
BEFORE INSERT ON STOCK 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT STOCK_SEQ5.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TAIEF"."STOCK_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table REVENU
--------------------------------------------------------

  ALTER TABLE "TAIEF"."REVENU" ADD CONSTRAINT "REVENU_PK" PRIMARY KEY ("ID_REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."REVENU" MODIFY ("ID_REV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPENSE
--------------------------------------------------------

  ALTER TABLE "TAIEF"."DEPENSE" ADD CONSTRAINT "DEPENSE_PK" PRIMARY KEY ("ID_DEP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."DEPENSE" MODIFY ("ID_DEP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STOCK
--------------------------------------------------------

  ALTER TABLE "TAIEF"."STOCK" ADD CONSTRAINT "STOCK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."STOCK" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROFIL
--------------------------------------------------------

  ALTER TABLE "TAIEF"."PROFIL" ADD CONSTRAINT "PROFIL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."PROFIL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LIVREUR
--------------------------------------------------------

  ALTER TABLE "TAIEF"."LIVREUR" ADD CONSTRAINT "LIVREUR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."LIVREUR" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "TAIEF"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID_CLI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."CLIENT" MODIFY ("ID_CLI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURN
--------------------------------------------------------

  ALTER TABLE "TAIEF"."FOURN" ADD CONSTRAINT "FOURN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."FOURN" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "TAIEF"."PRODUIT" ADD CONSTRAINT "PRODUIT_PK" PRIMARY KEY ("ID_PRODUIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."PRODUIT" MODIFY ("ID_PRODUIT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LIVRAISON
--------------------------------------------------------

  ALTER TABLE "TAIEF"."LIVRAISON" ADD CONSTRAINT "LIVRAISON_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."LIVRAISON" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "TAIEF"."COMMANDE" ADD CONSTRAINT "COMMANDE_PK" PRIMARY KEY ("ID_COM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "TAIEF"."COMMANDE" MODIFY ("ID_COM" NOT NULL ENABLE);
